<?php

namespace App\Support\Website;

/**
 * The 50 built-in templates.
 *
 * - "Crafted" templates point to a hand-built Blade theme
 *   (resources/views/websites/templates/{layout}).
 * - "Composed" templates use layout "composer": a unique combination of
 *   component variants (resources/views/components/company/{slot}/{variant})
 *   plus their own design system (theme, typography, scale, spacing, cards,
 *   labels, rhythm, animation, buttons, image shape) and brand defaults.
 *
 * TemplateSeeder writes these definitions to the `templates` table; admins
 * can then duplicate and tweak them (Admin → Templates).
 */
class TemplateLibrary
{
    public const CATEGORIES = [
        'corporate' => ['Corporate', 'Korporat, holding, BUMN dan grup usaha.'],
        'technology' => ['Technology', 'Software house, SaaS, AI dan perusahaan digital.'],
        'construction' => ['Construction', 'Kontraktor, engineering, arsitektur dan properti.'],
        'manufacturing' => ['Manufacturing', 'Pabrik, industri, logistik, otomotif dan energi.'],
        'finance' => ['Finance', 'Keuangan, investasi, perbankan, konsultan dan hukum.'],
        'healthcare' => ['Healthcare', 'Rumah sakit, klinik, farmasi dan wellness.'],
        'creative' => ['Creative', 'Agensi, studio branding, foto dan video.'],
        'retail' => ['Retail', 'Retail, lifestyle, F&B, fashion dan consumer brand.'],
        'education' => ['Education', 'Sekolah, universitas, pelatihan, NGO dan institusi.'],
        'premium' => ['Premium', 'Desain eksperimental & premium: Swiss, editorial, bento, luxury.'],
        'other' => ['Other', 'Template lainnya.'],
    ];

    /** Shop tokens per composed template: [product card, cart, shop hero]. */
    private const SHOP = [
        'business-grid' => ['bento', 'drawer', 'split'], 'corporate-dark' => ['modern', 'drawer', 'minimal'],
        'global-enterprise' => ['classic', 'page', 'banner'], 'tech-vision' => ['modern', 'drawer', 'split'],
        'ai-company' => ['modern', 'drawer', 'minimal'], 'digital-studio' => ['image', 'drawer', 'minimal'],
        'architecture-studio' => ['minimal', 'page', 'image'], 'engineering' => ['compact', 'page', 'banner'],
        'industrial' => ['compact', 'page', 'image'], 'property-developer' => ['luxury', 'page', 'image'],
        'factory' => ['compact', 'page', 'banner'], 'supply-chain' => ['horizontal', 'page', 'banner'],
        'automotive' => ['luxury', 'drawer', 'image'], 'energy' => ['classic', 'drawer', 'split'],
        'finance-elite' => ['classic', 'page', 'minimal'], 'investment' => ['minimal', 'page', 'minimal'],
        'banking-modern' => ['modern', 'page', 'split'], 'healthcare-modern' => ['classic', 'drawer', 'split'],
        'medical-center' => ['horizontal', 'page', 'banner'], 'pharmaceutical' => ['compact', 'page', 'minimal'],
        'wellness' => ['luxury', 'drawer', 'image'], 'healthcare-enterprise' => ['classic', 'page', 'banner'],
        'digital-agency' => ['bento', 'drawer', 'split'], 'branding-studio' => ['minimal', 'drawer', 'minimal'],
        'photography-studio' => ['image', 'drawer', 'image'], 'video-production' => ['image', 'drawer', 'image'],
        'retail-modern' => ['classic', 'drawer', 'banner'], 'lifestyle-brand' => ['image', 'drawer', 'image'],
        'food-beverage' => ['horizontal', 'drawer', 'image'], 'fashion-brand' => ['image', 'drawer', 'minimal'],
        'consumer-brand' => ['modern', 'drawer', 'split'], 'education-modern' => ['classic', 'page', 'banner'],
        'university' => ['horizontal', 'page', 'banner'], 'training-center' => ['modern', 'page', 'split'],
        'ngo-foundation' => ['classic', 'page', 'image'], 'government' => ['compact', 'page', 'banner'],
        'editorial' => ['minimal', 'page', 'minimal'], 'bento-modern' => ['bento', 'drawer', 'split'],
        'neo-luxury' => ['luxury', 'drawer', 'image'], 'future-enterprise' => ['modern', 'drawer', 'minimal'],
    ];

    private const SECTIONS = ['hero', 'clients', 'about', 'services', 'stats', 'products', 'projects', 'team', 'testimonials', 'gallery', 'cta', 'contact'];

    /**
     * @return array<int, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            // ------------------------------------------------------- Corporate & Business
            self::crafted('corporate-prime', 'Corporate Prime', 'corporate', 'Enterprise · Clean · Premium · Structured',
                'Enterprise yang bersih dan premium: top-bar kontak, hero split besar, navigasi korporat dan section yang terstruktur. Untuk perusahaan besar, holding, BUMN dan konsultan.', true, 'corporate'),
            self::crafted('executive', 'Executive', 'corporate', 'Luxury Corporate · Minimal · Elegant · Serif',
                'Korporat mewah: navy & emas, tipografi serif Cormorant, garis tipis dan foto sinematik dengan CTA minimal.', true),
            self::composed('business-grid', 'Business Grid', 'corporate', 'Modular Grid · Bento · Asymmetric · Modern Cards',
                'Grid modular dengan bento hero, kartu modern dan hierarki visual yang kuat — statistik, layanan dan portofolio dalam grid asimetris.',
                ['primary_color' => '#4f46e5', 'secondary_color' => '#0f172a', 'heading_font' => 'Inter Tight', 'body_font' => 'Inter', 'button_style' => 'rounded', 'border_radius' => 'xl'],
                ['navbar' => 'floating', 'hero' => 'bento', 'about' => 'bento', 'services' => 'bento', 'products' => 'grid', 'projects' => 'bento', 'team' => 'grid', 'testimonials' => 'masonry', 'gallery' => 'bento', 'cta' => 'card', 'contact' => 'cards', 'stats' => 'cards', 'clients' => 'grid', 'footer' => 'multicolumn', 'page-header' => 'banner'],
                ['theme' => 'soft', 'heading' => 'sans-tight', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'bordered', 'eyebrow' => 'pill', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'slide', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'stats', 'about', 'services', 'projects', 'clients', 'testimonials', 'products', 'team', 'gallery', 'cta', 'contact'], true),
            self::composed('corporate-dark', 'Corporate Dark', 'corporate', 'Dark Modern · High Contrast · Premium · Large Type',
                'Korporat gelap dan premium dengan kontras tinggi, tipografi besar dan aksen glass. Cocok untuk teknologi, keuangan dan konsultan.',
                ['primary_color' => '#38bdf8', 'secondary_color' => '#0a0d14', 'heading_font' => 'Sora', 'body_font' => 'Inter', 'button_style' => 'pill', 'border_radius' => 'lg'],
                ['navbar' => 'glass', 'hero' => 'dark', 'about' => 'stats', 'services' => 'numbered', 'products' => 'featured', 'projects' => 'featured', 'team' => 'portrait', 'testimonials' => 'quote', 'gallery' => 'strip', 'cta' => 'gradient', 'contact' => 'dark', 'stats' => 'dark', 'clients' => 'marquee', 'footer' => 'dark', 'page-header' => 'dark'],
                ['theme' => 'dark', 'heading' => 'sans-tight', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'wide', 'card' => 'glass', 'eyebrow' => 'line', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'reveal', 'button' => 'solid', 'image' => 'rounded', 'divider' => 'line']),
            self::composed('global-enterprise', 'Global Enterprise', 'corporate', 'International · Spacious · Sophisticated · Mega Menu',
                'Korporat internasional yang lapang: mega menu, hero peta kehadiran global, kantor cabang, anak perusahaan, statistik dan klien.',
                ['primary_color' => '#0b5cab', 'secondary_color' => '#062b52', 'heading_font' => 'Libre Franklin', 'body_font' => 'Libre Franklin', 'button_style' => 'square', 'border_radius' => 'sm'],
                ['navbar' => 'mega', 'hero' => 'globe', 'about' => 'mission', 'services' => 'tabs', 'products' => 'table', 'projects' => 'case-study', 'team' => 'leadership', 'testimonials' => 'split', 'gallery' => 'fullbleed', 'cta' => 'image', 'contact' => 'offices', 'stats' => 'split', 'clients' => 'logos', 'footer' => 'large', 'page-header' => 'split'],
                ['theme' => 'light', 'heading' => 'sans-bold', 'scale' => 'md', 'spacing' => 'airy', 'container' => 'wide', 'card' => 'plain', 'eyebrow' => 'line', 'align' => 'left', 'rhythm' => 'bands', 'animation' => 'fade', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'stats', 'about', 'clients', 'services', 'projects', 'team', 'products', 'testimonials', 'gallery', 'cta', 'contact'], true),

            // ------------------------------------------------------- Technology
            self::composed('tech-vision', 'Tech Vision', 'technology', 'Futuristic · Clean · Subtle Gradients · Large Type',
                'Teknologi futuristik yang tetap bersih: navbar transparan, hero gradien halus, tipografi besar yang ringan dan grid ikon.',
                ['primary_color' => '#6366f1', 'secondary_color' => '#0ea5e9', 'heading_font' => 'Outfit', 'body_font' => 'Inter', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'transparent', 'hero' => 'gradient', 'about' => 'image-text', 'services' => 'icon-grid', 'products' => 'carousel', 'projects' => 'horizontal', 'team' => 'hover-reveal', 'testimonials' => 'slider', 'gallery' => 'carousel', 'cta' => 'gradient', 'contact' => 'centered', 'stats' => 'minimal', 'clients' => 'marquee', 'footer' => 'centered', 'page-header' => 'minimal'],
                ['theme' => 'light', 'heading' => 'sans-light', 'scale' => 'xl', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'soft', 'eyebrow' => 'dot', 'align' => 'center', 'rhythm' => 'flat', 'animation' => 'zoom', 'button' => 'solid', 'image' => 'soft']),
            self::crafted('saas-modern', 'SaaS Modern', 'technology', 'SaaS Landing · Dashboard UI · Feature Blocks · Metrics',
                'Gaya landing page SaaS: navbar pill transparan, hero gradien dengan mockup dashboard mengambang, metrik dan feature cards.', true, 'modern-business'),
            self::composed('ai-company', 'AI Company', 'technology', 'AI · Futuristic · Glow Gradient · Dark/Light Contrast',
                'Perusahaan AI: hero gelap berpusat dengan visual abstrak bercahaya, label monospace dan kontras section gelap-terang.',
                ['primary_color' => '#a78bfa', 'secondary_color' => '#22d3ee', 'heading_font' => 'Geist', 'body_font' => 'Geist', 'button_style' => 'pill', 'border_radius' => 'lg'],
                ['navbar' => 'floating', 'hero' => 'centered', 'about' => 'split', 'services' => 'sticky', 'products' => 'featured', 'projects' => 'list-hover', 'team' => 'grid', 'testimonials' => 'marquee', 'gallery' => 'bento', 'cta' => 'gradient', 'contact' => 'minimal', 'stats' => 'band', 'clients' => 'marquee', 'footer' => 'wordmark', 'page-header' => 'dark'],
                ['theme' => 'midnight', 'heading' => 'sans-tight', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'normal', 'card' => 'glass', 'eyebrow' => 'mono', 'align' => 'center', 'rhythm' => 'contrast', 'animation' => 'reveal', 'button' => 'solid', 'image' => 'rounded'],
                ['hero', 'clients', 'services', 'about', 'stats', 'products', 'projects', 'testimonials', 'team', 'gallery', 'cta', 'contact'], true),
            self::composed('digital-studio', 'Digital Studio', 'technology', 'Creative Tech · Oversized Type · Image Grid · Interactive',
                'Studio digital: tipografi raksasa, marquee gambar, grid proyek interaktif dan layanan dalam baris hover besar.',
                ['primary_color' => '#ff5a1f', 'secondary_color' => '#111111', 'heading_font' => 'Bricolage Grotesque', 'body_font' => 'DM Sans', 'button_style' => 'pill', 'border_radius' => 'lg'],
                ['navbar' => 'minimal', 'hero' => 'marquee', 'about' => 'editorial', 'services' => 'horizontal', 'products' => 'carousel', 'projects' => 'masonry', 'team' => 'hover-reveal', 'testimonials' => 'cards', 'gallery' => 'masonry', 'cta' => 'minimal', 'contact' => 'split', 'stats' => 'minimal', 'clients' => 'grid', 'footer' => 'wordmark', 'page-header' => 'editorial'],
                ['theme' => 'light', 'heading' => 'sans-tight', 'scale' => 'xxl', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'flat', 'eyebrow' => 'bracket', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'slide', 'button' => 'arrow', 'image' => 'rounded', 'divider' => 'line'],
                ['hero', 'projects', 'services', 'about', 'clients', 'stats', 'testimonials', 'team', 'products', 'gallery', 'cta', 'contact']),
            self::crafted('cyber-modern', 'Cyber Modern', 'technology', 'Dark · Technical · Grid Background · Monospace',
                'Teknis dan gelap: latar grid & dot, glow terkontrol, label monospace, kartu terminal dan bento layanan — tetap profesional.', false, 'technology'),

            // ------------------------------------------------------- Construction & Engineering
            self::crafted('construction-pro', 'Construction Pro', 'construction', 'Bold · Industrial · Large Project Photography',
                'Kontraktor yang tegas: uppercase tebal, aksen kuning, statistik besar, layanan bernomor, masonry proyek dan badge mutu.', true, 'construction'),
            self::composed('architecture-studio', 'Architecture Studio', 'construction', 'Architectural · Minimal · Editorial · Large Photography',
                'Studio arsitektur editorial: navigasi minimal, foto besar layar penuh, layanan sebagai daftar minimal dan proyek bergantian.',
                ['primary_color' => '#8b6f47', 'secondary_color' => '#1c1917', 'heading_font' => 'Instrument Serif', 'body_font' => 'Hanken Grotesk', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'minimal', 'hero' => 'fullimage', 'about' => 'editorial', 'services' => 'minimal-list', 'products' => 'list', 'projects' => 'alternating', 'team' => 'list', 'testimonials' => 'minimal', 'gallery' => 'masonry', 'cta' => 'minimal', 'contact' => 'minimal', 'stats' => 'minimal', 'clients' => 'logos', 'footer' => 'minimal', 'page-header' => 'image'],
                ['theme' => 'cream', 'heading' => 'serif-light', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'wide', 'card' => 'plain', 'eyebrow' => 'number', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'fade', 'button' => 'underline', 'image' => 'square', 'divider' => 'line'],
                ['hero', 'about', 'projects', 'services', 'stats', 'team', 'gallery', 'testimonials', 'clients', 'products', 'cta', 'contact']),
            self::composed('engineering', 'Engineering', 'construction', 'Technical · Structured · Diagrams · Statistics',
                'Engineering yang terstruktur: top-bar utilitas, hero statistik dengan grid teknis, proses bernomor, tabel kapabilitas dan studi kasus.',
                ['primary_color' => '#0369a1', 'secondary_color' => '#0c1a2b', 'heading_font' => 'IBM Plex Sans', 'body_font' => 'IBM Plex Sans', 'button_style' => 'square', 'border_radius' => 'sm'],
                ['navbar' => 'topbar', 'hero' => 'stats', 'about' => 'timeline', 'services' => 'timeline', 'products' => 'table', 'projects' => 'case-study', 'team' => 'horizontal', 'testimonials' => 'cards', 'gallery' => 'grid', 'cta' => 'split', 'contact' => 'cards', 'stats' => 'band', 'clients' => 'grid', 'footer' => 'institutional', 'page-header' => 'banner'],
                ['theme' => 'soft', 'heading' => 'sans-bold', 'scale' => 'md', 'spacing' => 'compact', 'container' => 'normal', 'card' => 'bordered', 'eyebrow' => 'number', 'align' => 'left', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'clients', 'about', 'services', 'projects', 'stats', 'products', 'team', 'testimonials', 'gallery', 'cta', 'contact']),
            self::composed('industrial', 'Industrial', 'construction', 'Industrial · Bold Typography · Dark Sections',
                'Industrial berat: tipografi condensed tebal, hero foto sinematik, section gelap, proyek layar penuh dan statistik besar.',
                ['primary_color' => '#f97316', 'secondary_color' => '#18181b', 'heading_font' => 'Barlow Condensed', 'body_font' => 'Barlow', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'dark', 'hero' => 'cinematic', 'about' => 'fullwidth', 'services' => 'image-cards', 'products' => 'showcase', 'projects' => 'fullwidth', 'team' => 'grid', 'testimonials' => 'quote', 'gallery' => 'strip', 'cta' => 'image', 'contact' => 'dark', 'stats' => 'dark', 'clients' => 'logos', 'footer' => 'dark', 'page-header' => 'image'],
                ['theme' => 'graphite', 'heading' => 'condensed', 'scale' => 'xxl', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'flat', 'eyebrow' => 'line', 'align' => 'left', 'rhythm' => 'contrast', 'animation' => 'slide', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'stats', 'about', 'services', 'projects', 'products', 'gallery', 'team', 'testimonials', 'clients', 'cta', 'contact']),
            self::composed('property-developer', 'Property Developer', 'construction', 'Luxury Real Estate · Elegant · Property Cards',
                'Developer properti mewah: hero slider foto properti, kartu unit dengan harga, galeri penuh dan kontak marketing gallery.',
                ['primary_color' => '#b08d57', 'secondary_color' => '#1f2a24', 'heading_font' => 'Playfair Display', 'body_font' => 'Jost', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'transparent', 'hero' => 'slider', 'about' => 'split', 'services' => 'image-cards', 'products' => 'showcase', 'projects' => 'grid', 'team' => 'horizontal', 'testimonials' => 'split', 'gallery' => 'fullbleed', 'cta' => 'image', 'contact' => 'map', 'stats' => 'split', 'clients' => 'logos', 'footer' => 'contact', 'page-header' => 'image'],
                ['theme' => 'cream', 'heading' => 'serif', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'wide', 'card' => 'plain', 'eyebrow' => 'line', 'align' => 'center', 'rhythm' => 'alternate', 'animation' => 'fade', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'about', 'products', 'stats', 'projects', 'services', 'gallery', 'testimonials', 'team', 'clients', 'cta', 'contact'], true),

            // ------------------------------------------------------- Manufacturing & Industry
            self::crafted('manufacturing-pro', 'Manufacturing Pro', 'manufacturing', 'Industrial Corporate · Clean · Data Presentation',
                'Industrial korporat yang bersih: katalog produk bertab, proses produksi bernomor, sertifikasi dan tabel klien.', false, 'manufacturing'),
            self::composed('factory', 'Factory', 'manufacturing', 'Bold · Image Heavy · Production & Facilities',
                'Pabrik yang tegas dan kaya foto: hero kolase fasilitas, katalog produk, mesin & fasilitas sebagai kartu bergambar, sertifikasi.',
                ['primary_color' => '#dc2626', 'secondary_color' => '#1f2937', 'heading_font' => 'Archivo', 'body_font' => 'Archivo', 'button_style' => 'square', 'border_radius' => 'sm'],
                ['navbar' => 'topbar', 'hero' => 'collage', 'about' => 'stats', 'services' => 'image-cards', 'products' => 'catalog', 'projects' => 'grid', 'team' => 'grid', 'testimonials' => 'cards', 'gallery' => 'bento', 'cta' => 'band', 'contact' => 'cards', 'stats' => 'band', 'clients' => 'logos', 'footer' => 'multicolumn', 'page-header' => 'banner'],
                ['theme' => 'light', 'heading' => 'display-upper', 'scale' => 'lg', 'spacing' => 'compact', 'container' => 'wide', 'card' => 'shadow', 'eyebrow' => 'plain', 'align' => 'left', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'stats', 'about', 'products', 'services', 'gallery', 'projects', 'clients', 'testimonials', 'team', 'cta', 'contact']),
            self::composed('supply-chain', 'Supply Chain', 'manufacturing', 'Logistics · Modern Grid · Map-inspired',
                'Logistik modern: hero peta jaringan, layanan dalam grid ikon, jaringan gudang & kantor, statistik armada dan pelacakan.',
                ['primary_color' => '#0d9488', 'secondary_color' => '#0b1b2b', 'heading_font' => 'Manrope', 'body_font' => 'Manrope', 'button_style' => 'rounded', 'border_radius' => 'md'],
                ['navbar' => 'classic', 'hero' => 'globe', 'about' => 'two-column', 'services' => 'icon-grid', 'products' => 'table', 'projects' => 'bento', 'team' => 'list', 'testimonials' => 'slider', 'gallery' => 'grid', 'cta' => 'contact', 'contact' => 'offices', 'stats' => 'cards', 'clients' => 'marquee', 'footer' => 'split', 'page-header' => 'split'],
                ['theme' => 'soft', 'heading' => 'sans-bold', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'shadow', 'eyebrow' => 'dot', 'align' => 'left', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'rounded'],
                ['hero', 'stats', 'services', 'about', 'clients', 'projects', 'products', 'testimonials', 'team', 'gallery', 'cta', 'contact']),
            self::composed('automotive', 'Automotive', 'manufacturing', 'Premium Automotive · Dark · Product Showcase',
                'Otomotif premium: hero produk besar di section gelap, showcase produk bergantian, spesifikasi dan jaringan dealer.',
                ['primary_color' => '#e11d48', 'secondary_color' => '#0a0a0a', 'heading_font' => 'Red Hat Display', 'body_font' => 'Red Hat Display', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'glass', 'hero' => 'product', 'about' => 'fullwidth', 'services' => 'tabs', 'products' => 'showcase', 'projects' => 'horizontal', 'team' => 'carousel', 'testimonials' => 'quote', 'gallery' => 'carousel', 'cta' => 'image', 'contact' => 'offices', 'stats' => 'dark', 'clients' => 'logos', 'footer' => 'dark', 'page-header' => 'dark'],
                ['theme' => 'graphite', 'heading' => 'sans-tight', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'wide', 'card' => 'flat', 'eyebrow' => 'line', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'zoom', 'button' => 'solid', 'image' => 'square', 'divider' => 'line'],
                ['hero', 'products', 'about', 'stats', 'services', 'projects', 'gallery', 'testimonials', 'team', 'clients', 'cta', 'contact']),
            self::composed('energy', 'Energy', 'manufacturing', 'Energy · Corporate · Environmental · Data Visualization',
                'Perusahaan energi: hero full image dengan statistik kapasitas, visualisasi data, nilai keberlanjutan dan proyek pembangkit.',
                ['primary_color' => '#16a34a', 'secondary_color' => '#052e2b', 'heading_font' => 'Plus Jakarta Sans', 'body_font' => 'Inter', 'button_style' => 'pill', 'border_radius' => 'lg'],
                ['navbar' => 'transparent', 'hero' => 'overlap', 'about' => 'values', 'services' => 'cards', 'products' => 'grid', 'projects' => 'featured', 'team' => 'leadership', 'testimonials' => 'cards', 'gallery' => 'fullbleed', 'cta' => 'band', 'contact' => 'split', 'stats' => 'split', 'clients' => 'logos', 'footer' => 'newsletter', 'page-header' => 'image'],
                ['theme' => 'light', 'heading' => 'sans-bold', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'elevated', 'eyebrow' => 'pill', 'align' => 'left', 'rhythm' => 'accent', 'animation' => 'slide', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'stats', 'about', 'services', 'projects', 'clients', 'gallery', 'team', 'testimonials', 'products', 'cta', 'contact']),

            // ------------------------------------------------------- Finance & Professional Services
            self::composed('finance-elite', 'Finance Elite', 'finance', 'Premium Finance · Sophisticated · Conservative Modern',
                'Keuangan premium yang konservatif-modern: navigasi berpusat, hero potret eksekutif, kepemimpinan dan statistik aset kelolaan.',
                ['primary_color' => '#b8892d', 'secondary_color' => '#0f1d33', 'heading_font' => 'Source Serif 4', 'body_font' => 'Inter', 'button_style' => 'square', 'border_radius' => 'sm'],
                ['navbar' => 'centered', 'hero' => 'portrait', 'about' => 'ceo', 'services' => 'accordion', 'products' => 'table', 'projects' => 'editorial', 'team' => 'leadership', 'testimonials' => 'quote', 'gallery' => 'grid', 'cta' => 'split', 'contact' => 'split', 'stats' => 'band', 'clients' => 'logos', 'footer' => 'large', 'page-header' => 'editorial'],
                ['theme' => 'light', 'heading' => 'serif', 'scale' => 'lg', 'spacing' => 'airy', 'container' => 'normal', 'card' => 'bordered', 'eyebrow' => 'line', 'align' => 'center', 'rhythm' => 'accent', 'animation' => 'fade', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'stats', 'about', 'services', 'team', 'testimonials', 'products', 'projects', 'clients', 'gallery', 'cta', 'contact'], true),
            self::composed('investment', 'Investment', 'finance', 'Investment Firm · Elegant · Minimal · Data Driven',
                'Firma investasi minimal dan berbasis data: hero minimal, statistik kinerja, portofolio investasi sebagai daftar dengan hover gambar.',
                ['primary_color' => '#0f766e', 'secondary_color' => '#111827', 'heading_font' => 'Newsreader', 'body_font' => 'Inter', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'split', 'hero' => 'minimal', 'about' => 'stats', 'services' => 'numbered', 'products' => 'list', 'projects' => 'list-hover', 'team' => 'list', 'testimonials' => 'minimal', 'gallery' => 'strip', 'cta' => 'minimal', 'contact' => 'minimal', 'stats' => 'minimal', 'clients' => 'grid', 'footer' => 'split', 'page-header' => 'minimal'],
                ['theme' => 'mono', 'heading' => 'serif-light', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'normal', 'card' => 'plain', 'eyebrow' => 'number', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'fade', 'button' => 'underline', 'image' => 'square', 'divider' => 'line'],
                ['hero', 'stats', 'about', 'services', 'projects', 'team', 'clients', 'products', 'testimonials', 'gallery', 'cta', 'contact']),
            self::composed('banking-modern', 'Banking Modern', 'finance', 'Trustworthy · Clean · Modern Financial UI',
                'Perbankan modern yang terpercaya: hero produk dengan kartu UI keuangan, produk tabungan & pinjaman, keamanan dan kantor cabang.',
                ['primary_color' => '#1d4ed8', 'secondary_color' => '#0b1f44', 'heading_font' => 'Figtree', 'body_font' => 'Figtree', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'mega', 'hero' => 'dashboard', 'about' => 'two-column', 'services' => 'tabs', 'products' => 'grid', 'projects' => 'grid', 'team' => 'horizontal', 'testimonials' => 'slider', 'gallery' => 'grid', 'cta' => 'card', 'contact' => 'offices', 'stats' => 'cards', 'clients' => 'logos', 'footer' => 'institutional', 'page-header' => 'banner'],
                ['theme' => 'soft', 'heading' => 'sans-bold', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'shadow', 'eyebrow' => 'pill', 'align' => 'center', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'products', 'stats', 'services', 'about', 'testimonials', 'projects', 'team', 'clients', 'gallery', 'cta', 'contact']),
            self::crafted('consulting', 'Consulting', 'finance', 'Professional Consulting · Typography Focused · Editorial',
                'Konsultan editorial: serif elegan, banyak ruang putih, layanan bernomor romawi dan slider kutipan besar.', false, 'consulting'),
            self::crafted('legal-professional', 'Legal Professional', 'finance', 'Premium Law Firm · Formal Modern · Serif + Sans',
                'Firma hukum premium: kombinasi serif & sans, kartu janji temu, area praktik bertab dan informasi yang terstruktur.', false, 'professional-services'),

            // ------------------------------------------------------- Healthcare
            self::composed('healthcare-modern', 'Healthcare Modern', 'healthcare', 'Clean · Trustworthy · Bright · Spacious',
                'Layanan kesehatan modern yang cerah dan lapang: hero split ramah, layanan ikon, dokter, jam praktik dan janji temu.',
                ['primary_color' => '#0891b2', 'secondary_color' => '#0f3d4c', 'heading_font' => 'Lexend', 'body_font' => 'Nunito Sans', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'classic', 'hero' => 'split', 'about' => 'image-text', 'services' => 'icon-grid', 'products' => 'grid', 'projects' => 'grid', 'team' => 'grid', 'testimonials' => 'cards', 'gallery' => 'grid', 'cta' => 'card', 'contact' => 'cards', 'stats' => 'cards', 'clients' => 'logos', 'footer' => 'contact', 'page-header' => 'banner'],
                ['theme' => 'light', 'heading' => 'sans-bold', 'scale' => 'lg', 'spacing' => 'airy', 'container' => 'normal', 'card' => 'soft', 'eyebrow' => 'pill', 'align' => 'center', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'services', 'about', 'stats', 'team', 'testimonials', 'products', 'gallery', 'projects', 'clients', 'cta', 'contact'], true),
            self::composed('medical-center', 'Medical Center', 'healthcare', 'Professional Healthcare · Service Cards · Doctors · Facilities',
                'Pusat medis profesional: top-bar darurat, hero full image dengan kartu janji, layanan bergambar, dokter dan fasilitas.',
                ['primary_color' => '#2563eb', 'secondary_color' => '#0f766e', 'heading_font' => 'Poppins', 'body_font' => 'Inter', 'button_style' => 'rounded', 'border_radius' => 'lg'],
                ['navbar' => 'topbar', 'hero' => 'overlap', 'about' => 'two-column', 'services' => 'image-cards', 'products' => 'list', 'projects' => 'grid', 'team' => 'horizontal', 'testimonials' => 'masonry', 'gallery' => 'bento', 'cta' => 'contact', 'contact' => 'map', 'stats' => 'band', 'clients' => 'grid', 'footer' => 'multicolumn', 'page-header' => 'image'],
                ['theme' => 'soft', 'heading' => 'sans-bold', 'scale' => 'md', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'shadow', 'eyebrow' => 'plain', 'align' => 'left', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'rounded'],
                ['hero', 'stats', 'services', 'team', 'about', 'gallery', 'testimonials', 'products', 'projects', 'clients', 'cta', 'contact']),
            self::composed('pharmaceutical', 'Pharmaceutical', 'healthcare', 'Scientific · Clean · Data Oriented',
                'Farmasi yang ilmiah: hero berpusat yang bersih, timeline riset, tabel produk, statistik dan sertifikasi mutu.',
                ['primary_color' => '#0e7490', 'secondary_color' => '#1e293b', 'heading_font' => 'Hanken Grotesk', 'body_font' => 'Hanken Grotesk', 'button_style' => 'rounded', 'border_radius' => 'md'],
                ['navbar' => 'classic', 'hero' => 'stats', 'about' => 'timeline', 'services' => 'accordion', 'products' => 'catalog', 'projects' => 'case-study', 'team' => 'grid', 'testimonials' => 'split', 'gallery' => 'grid', 'cta' => 'split', 'contact' => 'split', 'stats' => 'minimal', 'clients' => 'grid', 'footer' => 'institutional', 'page-header' => 'minimal'],
                ['theme' => 'light', 'heading' => 'sans-light', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'bordered', 'eyebrow' => 'bracket', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'fade', 'button' => 'solid', 'image' => 'rounded', 'divider' => 'line'],
                ['hero', 'clients', 'about', 'products', 'services', 'projects', 'stats', 'team', 'testimonials', 'gallery', 'cta', 'contact']),
            self::composed('wellness', 'Wellness', 'healthcare', 'Calm · Premium · Minimalist · Soft Hierarchy',
                'Wellness yang tenang: palet pasir, foto bentuk lengkung (arch), serif lembut, layanan sebagai daftar dan suasana premium.',
                ['primary_color' => '#7c8b6f', 'secondary_color' => '#3f3a33', 'heading_font' => 'Fraunces', 'body_font' => 'Jost', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'centered', 'hero' => 'portrait', 'about' => 'story', 'services' => 'minimal-list', 'products' => 'carousel', 'projects' => 'alternating', 'team' => 'portrait', 'testimonials' => 'quote', 'gallery' => 'masonry', 'cta' => 'minimal', 'contact' => 'centered', 'stats' => 'minimal', 'clients' => 'logos', 'footer' => 'centered', 'page-header' => 'editorial'],
                ['theme' => 'sand', 'heading' => 'serif-light', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'narrow', 'card' => 'plain', 'eyebrow' => 'dot', 'align' => 'center', 'rhythm' => 'alternate', 'animation' => 'fade', 'button' => 'solid', 'image' => 'arch'],
                ['hero', 'about', 'services', 'products', 'gallery', 'testimonials', 'team', 'stats', 'projects', 'clients', 'cta', 'contact']),
            self::composed('healthcare-enterprise', 'Healthcare Enterprise', 'healthcare', 'Institutional · Corporate · Hospital Group',
                'Grup rumah sakit berskala besar: mega menu, hero statistik jaringan, jaringan rumah sakit, kepemimpinan dan footer institusional.',
                ['primary_color' => '#0f766e', 'secondary_color' => '#0b2540', 'heading_font' => 'Public Sans', 'body_font' => 'Public Sans', 'button_style' => 'rounded', 'border_radius' => 'md'],
                ['navbar' => 'mega', 'hero' => 'panels', 'about' => 'mission', 'services' => 'tabs', 'products' => 'table', 'projects' => 'bento', 'team' => 'leadership', 'testimonials' => 'cards', 'gallery' => 'fullbleed', 'cta' => 'band', 'contact' => 'offices', 'stats' => 'band', 'clients' => 'logos', 'footer' => 'institutional', 'page-header' => 'split'],
                ['theme' => 'light', 'heading' => 'sans-bold', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'bordered', 'eyebrow' => 'line', 'align' => 'left', 'rhythm' => 'bands', 'animation' => 'slide', 'button' => 'solid', 'image' => 'rounded'],
                ['hero', 'stats', 'about', 'services', 'projects', 'team', 'testimonials', 'clients', 'gallery', 'products', 'cta', 'contact']),

            // ------------------------------------------------------- Creative & Agency
            self::crafted('creative-agency', 'Creative Agency', 'creative', 'Bold · Experimental · Large Type · Color Blocks',
                'Agensi kreatif yang berani: tipografi raksasa, sticker berputar, marquee, grid asimetris dan menu off-canvas.', true, 'creative-agency'),
            self::composed('digital-agency', 'Digital Agency', 'creative', 'Modern · Animated · Interactive · Portfolio Focused',
                'Agensi digital yang interaktif: navbar floating, hero kolase, portofolio horizontal, layanan bertab dan marquee klien.',
                ['primary_color' => '#7c3aed', 'secondary_color' => '#0f0a1e', 'heading_font' => 'Syne', 'body_font' => 'DM Sans', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'floating', 'hero' => 'collage', 'about' => 'bento', 'services' => 'accordion', 'products' => 'grid', 'projects' => 'horizontal', 'team' => 'carousel', 'testimonials' => 'marquee', 'gallery' => 'carousel', 'cta' => 'gradient', 'contact' => 'split', 'stats' => 'cards', 'clients' => 'marquee', 'footer' => 'cta', 'page-header' => 'minimal'],
                ['theme' => 'light', 'heading' => 'sans-tight', 'scale' => 'xxl', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'flat', 'eyebrow' => 'pill', 'align' => 'left', 'rhythm' => 'accent', 'animation' => 'zoom', 'button' => 'arrow', 'image' => 'soft'],
                ['hero', 'clients', 'projects', 'services', 'stats', 'about', 'testimonials', 'team', 'gallery', 'products', 'cta', 'contact'], true),
            self::composed('branding-studio', 'Branding Studio', 'creative', 'Editorial · Typography Heavy · Artistic',
                'Studio branding editorial: hero sampul majalah, tipografi serif besar, about editorial dan proyek gaya majalah.',
                ['primary_color' => '#c2410c', 'secondary_color' => '#1c1917', 'heading_font' => 'DM Serif Display', 'body_font' => 'Epilogue', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'editorial', 'hero' => 'editorial', 'about' => 'editorial', 'services' => 'numbered', 'products' => 'list', 'projects' => 'editorial', 'team' => 'hover-reveal', 'testimonials' => 'quote', 'gallery' => 'masonry', 'cta' => 'minimal', 'contact' => 'minimal', 'stats' => 'minimal', 'clients' => 'grid', 'footer' => 'wordmark', 'page-header' => 'editorial'],
                ['theme' => 'cream', 'heading' => 'serif', 'scale' => 'xxl', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'plain', 'eyebrow' => 'number', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'reveal', 'button' => 'underline', 'image' => 'square', 'divider' => 'line'],
                ['hero', 'projects', 'about', 'services', 'clients', 'team', 'testimonials', 'stats', 'gallery', 'products', 'cta', 'contact']),
            self::composed('photography-studio', 'Photography Studio', 'creative', 'Image First · Minimal Navigation · Fullscreen Photography',
                'Studio foto yang mengutamakan gambar: navigasi sidebar minimal, slider foto layar penuh, galeri masonry dan portofolio layar penuh.',
                ['primary_color' => '#e5e5e5', 'secondary_color' => '#0a0a0a', 'heading_font' => 'Tenor Sans', 'body_font' => 'Work Sans', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'sidebar', 'hero' => 'slider', 'about' => 'split', 'services' => 'minimal-list', 'products' => 'list', 'projects' => 'fullwidth', 'team' => 'list', 'testimonials' => 'minimal', 'gallery' => 'masonry', 'cta' => 'minimal', 'contact' => 'minimal', 'stats' => 'minimal', 'clients' => 'logos', 'footer' => 'minimal', 'page-header' => 'image'],
                ['theme' => 'graphite', 'heading' => 'serif-light', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'full', 'card' => 'plain', 'eyebrow' => 'plain', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'fade', 'button' => 'underline', 'image' => 'square'],
                ['hero', 'gallery', 'projects', 'about', 'services', 'testimonials', 'products', 'team', 'stats', 'clients', 'cta', 'contact']),
            self::composed('video-production', 'Video Production', 'creative', 'Cinematic · Dark · Large Media · Portfolio',
                'Rumah produksi video sinematik: video hero, section gelap, portofolio besar layar penuh dan showreel.',
                ['primary_color' => '#facc15', 'secondary_color' => '#050505', 'heading_font' => 'Unbounded', 'body_font' => 'Inter', 'button_style' => 'pill', 'border_radius' => 'md'],
                ['navbar' => 'transparent', 'hero' => 'video', 'about' => 'fullwidth', 'services' => 'horizontal', 'products' => 'featured', 'projects' => 'fullwidth', 'team' => 'portrait', 'testimonials' => 'marquee', 'gallery' => 'strip', 'cta' => 'image', 'contact' => 'dark', 'stats' => 'dark', 'clients' => 'marquee', 'footer' => 'wordmark', 'page-header' => 'dark'],
                ['theme' => 'dark', 'heading' => 'display-upper', 'scale' => 'xl', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'flat', 'eyebrow' => 'bracket', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'zoom', 'button' => 'solid', 'image' => 'rounded'],
                ['hero', 'clients', 'projects', 'services', 'about', 'stats', 'testimonials', 'team', 'gallery', 'products', 'cta', 'contact']),

            // ------------------------------------------------------- Retail & Consumer
            self::composed('retail-modern', 'Retail Modern', 'retail', 'E-commerce Inspired · Product Focused · Clean Cards',
                'Retail modern ala e-commerce: hero produk, katalog bertab dengan kartu produk bersih, kategori dan toko/outlet.',
                ['primary_color' => '#111827', 'secondary_color' => '#f59e0b', 'heading_font' => 'Albert Sans', 'body_font' => 'Albert Sans', 'button_style' => 'pill', 'border_radius' => 'lg'],
                ['navbar' => 'classic', 'hero' => 'product', 'about' => 'image-text', 'services' => 'icon-grid', 'products' => 'catalog', 'projects' => 'grid', 'team' => 'grid', 'testimonials' => 'cards', 'gallery' => 'grid', 'cta' => 'card', 'contact' => 'offices', 'stats' => 'cards', 'clients' => 'logos', 'footer' => 'newsletter', 'page-header' => 'banner'],
                ['theme' => 'light', 'heading' => 'sans-bold', 'scale' => 'lg', 'spacing' => 'compact', 'container' => 'wide', 'card' => 'flat', 'eyebrow' => 'plain', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'slide', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'products', 'services', 'about', 'stats', 'testimonials', 'gallery', 'projects', 'team', 'clients', 'cta', 'contact']),
            self::composed('lifestyle-brand', 'Lifestyle Brand', 'retail', 'Editorial · Premium · Photography Focused',
                'Lifestyle brand premium: hero kolase editorial, cerita brand, produk dalam carousel dan galeri bento.',
                ['primary_color' => '#9a3412', 'secondary_color' => '#292524', 'heading_font' => 'Cormorant Garamond', 'body_font' => 'Jost', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'centered', 'hero' => 'collage', 'about' => 'story', 'services' => 'image-cards', 'products' => 'carousel', 'projects' => 'editorial', 'team' => 'portrait', 'testimonials' => 'quote', 'gallery' => 'bento', 'cta' => 'image', 'contact' => 'centered', 'stats' => 'minimal', 'clients' => 'logos', 'footer' => 'newsletter', 'page-header' => 'editorial'],
                ['theme' => 'cream', 'heading' => 'serif', 'scale' => 'xl', 'spacing' => 'airy', 'container' => 'normal', 'card' => 'plain', 'eyebrow' => 'line', 'align' => 'center', 'rhythm' => 'alternate', 'animation' => 'fade', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'about', 'products', 'gallery', 'services', 'testimonials', 'projects', 'team', 'stats', 'clients', 'cta', 'contact']),
            self::composed('food-beverage', 'Food & Beverage', 'retail', 'Modern Restaurant · Large Photography · Elegant Type',
                'F&B modern: hero foto besar sinematik, menu sebagai daftar harga elegan, outlet, galeri dan reservasi.',
                ['primary_color' => '#b45309', 'secondary_color' => '#1c1310', 'heading_font' => 'Young Serif', 'body_font' => 'Work Sans', 'button_style' => 'pill', 'border_radius' => 'lg'],
                ['navbar' => 'transparent', 'hero' => 'cinematic', 'about' => 'split', 'services' => 'cards', 'products' => 'list', 'projects' => 'grid', 'team' => 'portrait', 'testimonials' => 'slider', 'gallery' => 'masonry', 'cta' => 'image', 'contact' => 'map', 'stats' => 'minimal', 'clients' => 'logos', 'footer' => 'contact', 'page-header' => 'image'],
                ['theme' => 'sand', 'heading' => 'serif', 'scale' => 'xl', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'flat', 'eyebrow' => 'dot', 'align' => 'center', 'rhythm' => 'contrast', 'animation' => 'fade', 'button' => 'solid', 'image' => 'arch'],
                ['hero', 'about', 'products', 'gallery', 'services', 'testimonials', 'team', 'stats', 'projects', 'clients', 'cta', 'contact'], true),
            self::composed('fashion-brand', 'Fashion Brand', 'retail', 'Luxury Fashion · Editorial · Asymmetric · Large Imagery',
                'Fashion mewah editorial: navigasi split, hero editorial asimetris, koleksi produk showcase dan lookbook masonry.',
                ['primary_color' => '#111111', 'secondary_color' => '#a3a3a3', 'heading_font' => 'Bodoni Moda', 'body_font' => 'Jost', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'split', 'hero' => 'editorial', 'about' => 'editorial', 'services' => 'minimal-list', 'products' => 'showcase', 'projects' => 'masonry', 'team' => 'portrait', 'testimonials' => 'minimal', 'gallery' => 'masonry', 'cta' => 'minimal', 'contact' => 'minimal', 'stats' => 'minimal', 'clients' => 'logos', 'footer' => 'minimal', 'page-header' => 'editorial'],
                ['theme' => 'mono', 'heading' => 'serif-light', 'scale' => 'xxl', 'spacing' => 'airy', 'container' => 'wide', 'card' => 'plain', 'eyebrow' => 'plain', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'reveal', 'button' => 'underline', 'image' => 'square'],
                ['hero', 'products', 'about', 'gallery', 'projects', 'testimonials', 'services', 'team', 'stats', 'clients', 'cta', 'contact']),
            self::composed('consumer-brand', 'Consumer Brand', 'retail', 'Colorful · Modern · Product Storytelling',
                'Consumer brand yang ceria: hero gradien, storytelling produk bergantian, nilai brand dan testimoni marquee.',
                ['primary_color' => '#f43f5e', 'secondary_color' => '#7c3aed', 'heading_font' => 'Rubik', 'body_font' => 'Rubik', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'floating', 'hero' => 'gradient', 'about' => 'values', 'services' => 'bento', 'products' => 'showcase', 'projects' => 'grid', 'team' => 'carousel', 'testimonials' => 'marquee', 'gallery' => 'carousel', 'cta' => 'gradient', 'contact' => 'centered', 'stats' => 'cards', 'clients' => 'marquee', 'footer' => 'cta', 'page-header' => 'banner'],
                ['theme' => 'light', 'heading' => 'sans-tight', 'scale' => 'xl', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'soft', 'eyebrow' => 'pill', 'align' => 'center', 'rhythm' => 'flat', 'animation' => 'zoom', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'products', 'about', 'stats', 'services', 'testimonials', 'gallery', 'team', 'projects', 'clients', 'cta', 'contact']),

            // ------------------------------------------------------- Education & Organization
            self::composed('education-modern', 'Education Modern', 'education', 'Friendly · Clean · Professional Institution',
                'Institusi pendidikan modern yang ramah: hero split, program sebagai kartu, guru, fasilitas dan testimoni orang tua.',
                ['primary_color' => '#2563eb', 'secondary_color' => '#f59e0b', 'heading_font' => 'Poppins', 'body_font' => 'Nunito Sans', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'classic', 'hero' => 'split', 'about' => 'values', 'services' => 'cards', 'products' => 'grid', 'projects' => 'grid', 'team' => 'grid', 'testimonials' => 'slider', 'gallery' => 'bento', 'cta' => 'band', 'contact' => 'cards', 'stats' => 'cards', 'clients' => 'logos', 'footer' => 'multicolumn', 'page-header' => 'banner'],
                ['theme' => 'light', 'heading' => 'sans-bold', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'shadow', 'eyebrow' => 'pill', 'align' => 'center', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'stats', 'about', 'services', 'products', 'team', 'gallery', 'testimonials', 'projects', 'clients', 'cta', 'contact']),
            self::composed('university', 'University', 'education', 'Institutional · Elegant · Academic',
                'Universitas yang elegan: top-bar institusional, hero full image dengan serif klasik, fakultas, pimpinan dan footer institusional.',
                ['primary_color' => '#7f1d1d', 'secondary_color' => '#1c1917', 'heading_font' => 'EB Garamond', 'body_font' => 'Source Serif 4', 'button_style' => 'square', 'border_radius' => 'sm'],
                ['navbar' => 'topbar', 'hero' => 'fullimage', 'about' => 'ceo', 'services' => 'tabs', 'products' => 'table', 'projects' => 'editorial', 'team' => 'leadership', 'testimonials' => 'split', 'gallery' => 'fullbleed', 'cta' => 'split', 'contact' => 'offices', 'stats' => 'band', 'clients' => 'grid', 'footer' => 'institutional', 'page-header' => 'image'],
                ['theme' => 'cream', 'heading' => 'serif', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'bordered', 'eyebrow' => 'line', 'align' => 'left', 'rhythm' => 'bands', 'animation' => 'fade', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'stats', 'about', 'services', 'team', 'projects', 'testimonials', 'gallery', 'products', 'clients', 'cta', 'contact']),
            self::composed('training-center', 'Training Center', 'education', 'Learning Platform · Course Cards · Instructors',
                'Pusat pelatihan ala platform belajar: hero dashboard kursus, kartu program dengan harga, instruktur dan testimoni alumni.',
                ['primary_color' => '#ea580c', 'secondary_color' => '#1e1b4b', 'heading_font' => 'Urbanist', 'body_font' => 'Inter', 'button_style' => 'rounded', 'border_radius' => 'lg'],
                ['navbar' => 'glass', 'hero' => 'dashboard', 'about' => 'stats', 'services' => 'timeline', 'products' => 'grid', 'projects' => 'bento', 'team' => 'horizontal', 'testimonials' => 'masonry', 'gallery' => 'grid', 'cta' => 'card', 'contact' => 'split', 'stats' => 'band', 'clients' => 'marquee', 'footer' => 'newsletter', 'page-header' => 'banner'],
                ['theme' => 'soft', 'heading' => 'sans-tight', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'elevated', 'eyebrow' => 'pill', 'align' => 'left', 'rhythm' => 'alternate', 'animation' => 'slide', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'clients', 'products', 'services', 'stats', 'team', 'testimonials', 'about', 'projects', 'gallery', 'cta', 'contact']),
            self::composed('ngo-foundation', 'NGO / Foundation', 'education', 'Mission Driven · Emotional Photography · Impact',
                'Yayasan berorientasi misi: hero foto emosional dengan kartu, statistik dampak, program, cerita perubahan dan ajakan donasi.',
                ['primary_color' => '#e11d48', 'secondary_color' => '#1f2937', 'heading_font' => 'Merriweather', 'body_font' => 'Work Sans', 'button_style' => 'pill', 'border_radius' => 'lg'],
                ['navbar' => 'classic', 'hero' => 'overlap', 'about' => 'mission', 'services' => 'image-cards', 'products' => 'grid', 'projects' => 'alternating', 'team' => 'grid', 'testimonials' => 'quote', 'gallery' => 'masonry', 'cta' => 'band', 'contact' => 'split', 'stats' => 'dark', 'clients' => 'logos', 'footer' => 'cta', 'page-header' => 'image'],
                ['theme' => 'cream', 'heading' => 'serif', 'scale' => 'lg', 'spacing' => 'normal', 'container' => 'normal', 'card' => 'shadow', 'eyebrow' => 'plain', 'align' => 'center', 'rhythm' => 'accent', 'animation' => 'slide', 'button' => 'solid', 'image' => 'rounded'],
                ['hero', 'stats', 'about', 'services', 'projects', 'testimonials', 'gallery', 'team', 'clients', 'products', 'cta', 'contact']),
            self::composed('government', 'Government / Institution', 'education', 'Formal · Trustworthy · Institutional · Clean Navigation',
                'Instansi pemerintah/lembaga yang formal: top-bar resmi, mega menu, hero panel, layanan publik dalam accordion dan footer institusional.',
                ['primary_color' => '#1e40af', 'secondary_color' => '#b91c1c', 'heading_font' => 'Public Sans', 'body_font' => 'Public Sans', 'button_style' => 'rounded', 'border_radius' => 'sm'],
                ['navbar' => 'topbar', 'hero' => 'panels', 'about' => 'ceo', 'services' => 'accordion', 'products' => 'table', 'projects' => 'list-hover', 'team' => 'leadership', 'testimonials' => 'minimal', 'gallery' => 'grid', 'cta' => 'contact', 'contact' => 'offices', 'stats' => 'band', 'clients' => 'grid', 'footer' => 'institutional', 'page-header' => 'banner'],
                ['theme' => 'light', 'heading' => 'sans-bold', 'scale' => 'md', 'spacing' => 'compact', 'container' => 'normal', 'card' => 'bordered', 'eyebrow' => 'plain', 'align' => 'left', 'rhythm' => 'alternate', 'animation' => 'fade', 'button' => 'solid', 'image' => 'square'],
                ['hero', 'services', 'stats', 'about', 'team', 'projects', 'products', 'gallery', 'testimonials', 'clients', 'cta', 'contact']),

            // ------------------------------------------------------- Premium / Experimental
            self::crafted('swiss-minimal', 'Swiss Minimal', 'premium', 'Swiss Design · Strict Grid · Typography · Monochrome',
                'Swiss minimal monokrom: grid ketat dua kolom, tipografi sebagai elemen utama, daftar bernomor dan tanpa ornamen.', false, 'minimal'),
            self::composed('editorial', 'Editorial', 'premium', 'Magazine · Large Serif · Asymmetric · Editorial Photography',
                'Gaya majalah: masthead editorial, hero sampul dengan serif raksasa, layout asimetris, kutipan besar dan foto editorial.',
                ['primary_color' => '#b91c1c', 'secondary_color' => '#111111', 'heading_font' => 'Gloock', 'body_font' => 'Newsreader', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'editorial', 'hero' => 'editorial', 'about' => 'story', 'services' => 'numbered', 'products' => 'list', 'projects' => 'editorial', 'team' => 'list', 'testimonials' => 'quote', 'gallery' => 'masonry', 'cta' => 'minimal', 'contact' => 'minimal', 'stats' => 'minimal', 'clients' => 'grid', 'footer' => 'large', 'page-header' => 'editorial'],
                ['theme' => 'light', 'heading' => 'serif', 'scale' => 'xxl', 'spacing' => 'normal', 'container' => 'wide', 'card' => 'plain', 'eyebrow' => 'number', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'reveal', 'button' => 'underline', 'image' => 'square', 'divider' => 'line'],
                ['hero', 'about', 'projects', 'services', 'testimonials', 'team', 'stats', 'gallery', 'clients', 'products', 'cta', 'contact']),
            self::composed('bento-modern', 'Bento Modern', 'premium', 'Bento Grid · Rounded Cards · Modular · Dashboard-inspired',
                'Bento modern: semua section disusun sebagai kartu bulat modular — hero bento, about bento, layanan bento, statistik kartu.',
                ['primary_color' => '#0ea5e9', 'secondary_color' => '#0f172a', 'heading_font' => 'Onest', 'body_font' => 'Onest', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'floating', 'hero' => 'bento', 'about' => 'bento', 'services' => 'bento', 'products' => 'carousel', 'projects' => 'bento', 'team' => 'hover-reveal', 'testimonials' => 'masonry', 'gallery' => 'bento', 'cta' => 'card', 'contact' => 'cards', 'stats' => 'cards', 'clients' => 'grid', 'footer' => 'split', 'page-header' => 'minimal'],
                ['theme' => 'soft', 'heading' => 'sans-tight', 'scale' => 'lg', 'spacing' => 'compact', 'container' => 'normal', 'card' => 'flat', 'eyebrow' => 'dot', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'zoom', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'stats', 'services', 'about', 'projects', 'clients', 'testimonials', 'team', 'products', 'gallery', 'cta', 'contact']),
            self::composed('neo-luxury', 'Neo Luxury', 'premium', 'Luxury · Dark · Elegant Typography · Premium Spacing',
                'Neo luxury: gelap dan elegan, serif tipis berukuran besar, spasi lapang, potret besar dan animasi halus.',
                ['primary_color' => '#d4af7a', 'secondary_color' => '#0c0b09', 'heading_font' => 'Italiana', 'body_font' => 'Jost', 'button_style' => 'square', 'border_radius' => 'none'],
                ['navbar' => 'centered', 'hero' => 'cinematic', 'about' => 'split', 'services' => 'sticky', 'products' => 'showcase', 'projects' => 'alternating', 'team' => 'portrait', 'testimonials' => 'quote', 'gallery' => 'fullbleed', 'cta' => 'minimal', 'contact' => 'centered', 'stats' => 'minimal', 'clients' => 'logos', 'footer' => 'centered', 'page-header' => 'dark'],
                ['theme' => 'graphite', 'heading' => 'serif-light', 'scale' => 'xxl', 'spacing' => 'airy', 'container' => 'normal', 'card' => 'outline', 'eyebrow' => 'line', 'align' => 'center', 'rhythm' => 'flat', 'animation' => 'fade', 'button' => 'underline', 'image' => 'arch'],
                ['hero', 'about', 'services', 'products', 'projects', 'gallery', 'testimonials', 'team', 'stats', 'clients', 'cta', 'contact'], true),
            self::composed('future-enterprise', 'Future Enterprise', 'premium', 'Futuristic Enterprise · Advanced Grid · Glass · Gradients',
                'Enterprise masa depan: grid lanjutan, efek glass halus, gradien canggih, tipografi besar — profesional, bukan gaming.',
                ['primary_color' => '#60a5fa', 'secondary_color' => '#c084fc', 'heading_font' => 'Inter Tight', 'body_font' => 'Inter', 'button_style' => 'pill', 'border_radius' => 'xl'],
                ['navbar' => 'glass', 'hero' => 'dashboard', 'about' => 'bento', 'services' => 'sticky', 'products' => 'featured', 'projects' => 'bento', 'team' => 'carousel', 'testimonials' => 'slider', 'gallery' => 'bento', 'cta' => 'gradient', 'contact' => 'dark', 'stats' => 'split', 'clients' => 'marquee', 'footer' => 'large', 'page-header' => 'dark'],
                ['theme' => 'midnight', 'heading' => 'sans-light', 'scale' => 'xxl', 'spacing' => 'airy', 'container' => 'wide', 'card' => 'glass', 'eyebrow' => 'bracket', 'align' => 'left', 'rhythm' => 'flat', 'animation' => 'reveal', 'button' => 'solid', 'image' => 'soft'],
                ['hero', 'clients', 'about', 'services', 'stats', 'projects', 'products', 'testimonials', 'team', 'gallery', 'cta', 'contact']),
        ];
    }

    /** @return array<string, mixed>|null */
    public static function find(string $slug): ?array
    {
        return collect(self::all())->firstWhere('slug', $slug);
    }

    private static function crafted(string $slug, string $name, string $category, string $style, string $description, bool $featured = false, ?string $layout = null): array
    {
        $layout ??= $slug;

        return [
            'slug' => $slug,
            'name' => $name,
            'category' => $category,
            'style' => $style,
            'description' => $description,
            'featured' => $featured,
            'layout' => $layout,
            'demo' => $layout,
            'settings' => [],
            'config' => null,
        ];
    }

    private static function composed(string $slug, string $name, string $category, string $style, string $description, array $brand, array $components, array $design, ?array $sections = null, bool $featured = false): array
    {
        return [
            'slug' => $slug,
            'name' => $name,
            'category' => $category,
            'style' => $style,
            'description' => $description,
            'featured' => $featured,
            'layout' => 'composer',
            'demo' => $slug,
            'settings' => $brand + ['sections' => $sections ?? self::SECTIONS],
            'config' => ['components' => $components, 'design' => $design + array_combine(['product_card', 'cart', 'shop_hero'], self::SHOP[$slug] ?? ['classic', 'drawer', 'banner'])],
        ];
    }
}
